version: "3"

services:
  admin-server:
    image: docker/wls12213-admin
    build:
      context: ./docker-images/admin-server
    ports:
      - 7001:7001
    networks: 
      - cluster_network
    environment:
      - DNS_NAME=wls-admin
      - CLUSTER_NAME=Cluster_MS
      - PRODUCTION_MODE=false
    container_name:  wls-admin
  ms01:
    image: docker/wls12213-node
    build: ./docker-images/node-server      
    ports:
      - 7002:7002
    networks: 
      - cluster_network
    environment:
      - CLUSTER_NAME=Cluster_MS
      - NODE_NAME=ms01
      - DNS_NAME=wls-ms01
      - NODE_LISTEN_PORT=7002
      - NODE_MANAGER_PORT=5556
      - PRODUCTION_MODE=false
    container_name:  wls-ms01
networks:
  cluster_network:
    driver: bridge